### ISSUE TITLE
ToS and Privacy Policy

### ISSUE THREAD

**Issue by CodyFreeman** [DevLifts/devlifts-static#6]
I cannot find terms of service or a privacy policy on your site. 

I'm very concerned neither of these things exist, considering the personal and potentially health related information we give you.

As you include EU countries in your user creation, you may need to get familiar with GDPR too.

**Comment by tricinel** [comment]
Correct me if I'm wrong...I'm not sure devlifts.io collects that information directly on the website. When I signed up, I filled in a typeform and payment was through Snipcart I believe. To my understanding then, devlifts is a data controller, rather than processor. I'm not a lawyer anyway 😉 

@jchiatt, it would be good to have GDPR compliance (as we understand it at least) and that would just involve in us creating a page on the site outlining what data is collected, how it's processed and for what purpose. I'd be happy to have a crack at it.

**Comment by CodyFreeman** [comment]
@tricinel Hopefully that part won't be bad. As you point out Devlifts is using a payment gateway :)

I'm more concerned about any information gathered through the premium service. I heard a call for before/after data and photos through their podcast. 

How a personalized diet plans stored? Health conditions? Notes, interview audio, that kind of thing...

I'm sorry if I'm being a paranoid downer.

**Comment by tricinel** [comment]
Yes, I completely understand. That's something that needs to be written down. The first step would be, like you suggest, a privacy page that can be improved upon :)

**Comment by jchiatt** [comment]
@CodyFreeman Thanks so much for the suggestion. We definitely should make a privacy policy. @tricinel is correct - we don't really store any data ourselves. As far as _what_ data, we ask questions about your past experience working out, your diet restrictions/preferences, your goals, etc.

We don't currently have a DevLifts app so we don't track anything in terms of health stats - it's completely up to you whether or not you'd like to keep us updated on any specific points of data in your private Slack channel.

Plans are delivered via Google Sheets, so that's how diet plans are stored. We don't record interviews unless you're a guest on a podcast, so we don't have any audio of you.

That's the tl;dr — but I'm definitely working to get something more official.

Thanks!

**Comment by jchiatt** [comment]
Completed in #13
